#!/bin/bash
# Incompatible initial and goal (fail)

STDOUT=/tmp/Nine20.stdout.$$
STDERR=/tmp/Nine20.stderr.$$
trap "/bin/rm -f $STDOUT $STDERR" 0 1 2 3 9 15

valgrind -q ./Nine20 10 1234-5678 ABC-DEFGH >$STDOUT 2>$STDERR
cat <$STDOUT ; echo ----- ; wc -l < $STDERR

echo =====

# Repeat last puzzle from Test #04
valgrind -q  ./Nine20 7 412-53786 12345678-
