#!/bin/bash
# Invalid WIDTH (error)

STDOUT=/tmp/Nine20.stdout.$$
STDERR=/tmp/Nine20.stderr.$$
trap "/bin/rm -f $STDOUT $STDERR" 0 1 2 3 9 15

valgrind -q >$STDOUT 2>$STDERR \
  ./Nine20 3 1 10 12- 12-
cat <$STDOUT ; echo ----- ; wc -l < $STDERR

echo =====

valgrind -q >$STDOUT 2>$STDERR \
  ./Nine20 2 6 10 123456789ab- 123456789ab-
cat <$STDOUT ; echo ----- ; wc -l < $STDERR

echo =====

valgrind -q >$STDOUT 2>$STDERR \
  ./Nine20 3 3a 10 12345678- 1234567-8
cat <$STDOUT ; echo ----- ; wc -l < $STDERR

echo =====

# Repeat last puzzle from Test #04
valgrind -q  ./Nine20 7 412-53786 12345678-
