#!/bin/bash
# INITIAL and GOAL have different lengths

STDOUT=/tmp/Nine20.stdout.$$
STDERR=/tmp/Nine20.stderr.$$
trap "/bin/rm -f $STDOUT $STDERR" 0 1 2 3 9 15

valgrind -q >$STDOUT 2>$STDERR \
  ./Nine20 10 1234-5678 123-4567
cat <$STDOUT ; echo ----- ; wc -l < $STDERR

echo =====

valgrind -q >$STDOUT 2>$STDERR \
  ./Nine20 10 1234-567  123-45678
cat <$STDOUT ; echo ----- ; wc -l < $STDERR

echo =====

# Repeat last puzzle from Test #04
valgrind -q  ./Nine20 7 412-53786 12345678-
