nonFlag should be replaced by nonFlag when this line is output.
=====
-Rr should appear in place of -Nn when this line is output.
=====
bcacbcbcaca bcacacbcbca
bcacbcbcaca bcacacbcbca
bcacbcbcaca bcacacbcbca
bcacbcbcaca bcacacbcbca
bcacbcbcaca bcacacbcbca
abcabab aaabbb
abcabbca aabcabb
abcbcabca aabcbcbca
bcacbcbcaca bcacacbcbca
abcabab aaabb
abcaabca abcaab
abcbcabca abcbcbca
bcacbcbcaca bcacacbcbca
bcacbcbcaca bcacacbcbca
bcacbcbcaca bcacacbcbca
bcacbcbcaca bcacacbcbca
-----
bcacbcbcaca bcacacbcbca
bcacbcbcaca bcacacbcbca
bcacbcbcaca bcacacbcbca
bcacbcbcaca bcacacbcbca
bcacbcbcaca bcacacbcbca
abcabab aaabbb
abcabbca aabcabb
abcbcabca aabcbcbca
bcacbcbcaca bcacacbcbca
abcabab aaabb
abcaabca abcaab
abcbcabca abcbcbca
bcacbcbcaca bcacacbcbca
bcacbcbcaca bcacacbcbca
bcacbcbcaca bcacacbcbca
bcacbcbcaca bcacacbcbca
=====
abcabbca aabcabb
abcabab aaabb
