#!/bin/bash
# Simple backtracking requires nothing (#backtracks = 107)

echo 'Simple backtracking requires nothing'
./Binpack 64 19 18 17 15 24 23 22 21 32 -ff -opt
echo

echo 'Simple backtracking requires nothing'
./Binpack 60 19 19 22 22 24 24 25 25 -opt -ffd
