#!/bin/bash
# bfd < bf < ff < ffd < bfd

echo 'ff vs ffd [ff = 2, ffd = 3, bf = bfd = opt = 2]'
./Binpack 13 9 2 2 5 5 3 -ff
./Binpack 13 9 2 2 5 5 3 -ffd
./Binpack 13 9 2 2 5 5 3 -opt
echo ---

echo 'bf < ff [ff = ffd = 3, bf = bfd = opt = 2]'
./Binpack 13 9 5 5 3 2 2 -bf
./Binpack 13 9 5 5 3 2 2 -ff
./Binpack 13 9 5 5 3 2 2 -opt
echo ---

echo 'bfd < bf [ff = ffd = bf = 3, bfd = opt = 2]'
./Binpack 13 9 3 5 5 2 2 -bfd
./Binpack 13 9 3 5 5 2 2 -bf
./Binpack 13 9 3 5 5 2 2 -opt
echo ---

echo 'ffd < bfd [ff = ffd = 2, bf = bfd = 3, opt = 2]'
./Binpack 24 16 9 9 4 4 3 3 -ffd
./Binpack 24 16 9 9 4 4 3 3 -bfd
./Binpack 24 16 9 9 4 4 3 3 -opt
echo ---

echo 'ffd < bfd [ff = 3, ffd = 2, bf = bfd = 3, opt = 2]'
./Binpack 24 9 4 4 3 3 16 9 -ffd
./Binpack 24 9 4 4 3 3 16 9 -bfd
./Binpack 24 9 4 4 3 3 16 9 -opt

# Requires nothing
