#!/bin/bash
# C necessary and sufficient

./Binpack 64 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 -opt
echo ---

# Requires C
# Fail: -optC
# backtracks(-opt)     = 3480007
# backtracks(-optABDE) = 3516247
# -ff = -ffd = -bf = -bfd = 9 = -opt > lower

# -opt < heuristic
./Binpack 64 19 18 17 15 24 23 22 21 32 -opt
