#!/bin/bash
# Heuristic D necessary and sufficient

./Binpack 71 50 49 48 47 46 45 44 43 42 41 40 20 20 20 20 20 20 20 20 20 20 20 20 -opt
echo ---

# Requires D
# backtracks(-opt) = 2036
# backtracks(-optABCE) = 239939
# -ff = -ffd = -bf = -bfd = 12 = -opt > lower

# -opt < heuristic
./Binpack 64 19 18 17 15 24 23 22 21 32 -opt
