#!/bin/bash
# Heuristic D or E necessary and sufficient

./Binpack 7 4 4 4 4 4 4 4 4 4 4 4 2 2 2 2 2 2 2 2 2 2 2 2 -opt
echo ---

# Requires D or E
# backtracks(-opt) = 0
# backtracks(-optABCE) = 239939
# backtracks(-optABCD) = 219713
# -ff = -ffd = -bf = -bfd = -opt = 12 > lower

# -opt < heuristic
./Binpack 64 19 18 17 15 24 23 22 21 32 -opt
