ffd best/worst
2 = opt = ffd < ff = bf = bfd = 3
-ff  3
-bf  3
-ffd 2
-bfd 3
2 = opt = ff = bf = bfd < ffd = 3
-ff  2
-bf  2
-ffd 3
-bfd 2

bfd best/worst
2 = opt = bfd < ff = ffd = bf = 3
-ff  3
-bf  3
-ffd 3
-bfd 2
2 = opt = ff = ffd = bf < bfd = 3
-ff  2
-bf  2
-ffd 2
-bfd 3

ff/ffd better/worse than bf/bfd
2 = opt = bf = bfd < ff = ffd = 3
-ff  3
-bf  2
-ffd 3
-bfd 2
2 = opt = ff = ffd < bf = bfd = 3
-ff  2
-bf  3
-ffd 2
-bfd 3
