#!/bin/bash
# valgrind II

echo 'Simple backtracking requires nothing'
valgrind -q ./Binpack 64 19 18 17 15 24 23 22 21 32 -ff -opt
echo

echo 'Simple backtracking requires nothing'
valgrind -q ./Binpack 60 19 19 22 22 24 24 25 25 -opt -ffd
