#!/bin/bash
# nRows < 1 or nCols < 1 (fail)

TESTS=/c/cs223/Hwk6/Tests

# nRows < 1
valgrind -q  <$TESTS/dict09 \
  ./Boggle  0 3 epiproust |& /usr/bin/wc -l

# nRows < 0
valgrind -q  <$TESTS/dict09 \
  ./Boggle -1 3 epiproust |& /usr/bin/wc -l

# nRows is empty string
# valgrind -q  <$TESTS/dict09 \
#   ./Boggle "" 3 epiproust |& /usr/bin/wc -l

# nRows begins with nondigit
# valgrind -q  <$TESTS/dict09 \
#   ./Boggle xy 3 epiproust |& /usr/bin/wc -l

# nRows contains nondigit
# valgrind -q  <$TESTS/dict09 \
#   ./Boggle 3z 3 epiproust |& /usr/bin/wc -l

echo -----

# nCols < 1
valgrind -q  <$TESTS/dict09 \
  ./Boggle 3  0 epiproust |& /usr/bin/wc -l

# nCols < 0
valgrind -q  <$TESTS/dict09 \
  ./Boggle 3 -1 epiproust |& /usr/bin/wc -l

# nCols is empty string
# valgrind -q  <$TESTS/dict09 \
#   ./Boggle 3 "" epiproust |& /usr/bin/wc -l

# nCols begins with nondigit
# valgrind -q  <$TESTS/dict09 \
#   ./Boggle 3 xy epiproust |& /usr/bin/wc -l

# nCols contains nondigit
# valgrind -q  <$TESTS/dict09 \
#   ./Boggle 3 3z epiproust |& /usr/bin/wc -l

echo -----

# Repeat Test #01
valgrind -q  <$TESTS/dict01 \
  ./Boggle 3 3 epiproust
