#!/bin/bash
# Random 4 x 4 board (traditional)
				
TESTS=/c/cs223/Hwk6/Tests

# /c/cs223/Doc/words (4+ letter words)
valgrind -q       <$TESTS/dict02 \
  ./Boggle -t 4 4 iddqndyetetuuwda

echo -----

# /c/cs223/Doc/words (6+ letter words)
/c/cs223/bin/run  <$TESTS/dict14 \
  ./Boggle -t 4 4 iroanrddhmebnrnr

echo -----

# /c/cs223/Doc/words (6+ letter words)
/c/cs223/bin/run  <$TESTS/dict02 \
  ./Boggle -t 4 4 tatefaeititnmiuo

echo -----

# /c/cs223/Doc/words (6+ letter words)
/c/cs223/bin/run  <$TESTS/dict02 \
  ./Boggle -t 4 4 itatogiaiuontdse
