#!/bin/bash
# Very large board (10x10)

TESTS=/c/cs223/Hwk6/Tests

sort -k 1.3 $TESTS/dict36              |  \
valgrind -q                               \
  ./Boggle 16 16 laiebncrocrserweuietdvaaotiideidetiiybcneiwapuuneoianaaeildcgnedyenwhebbdadtvaaeoyssztniueneiiiioltyexaxzeivtipahaiutxtfrwadgyawawvtunsuhqieaosyoeiapegjewenvealezfobonjgkoyailrdvrteouidanbtonadieeagrysvwiuaeavlkoqhotieletotnabirybpsneeaeyobabsriinieoeofndw
