#!/bin/bash
# Stable?: POS > 0

# t108x:
#   4--3--4--2--3--2--4--3--4--1--3--1--4--2--4--1--2--1--3--2--3--1--2--1--
#   2--2--3--3--4--4--1--1--3--3--4--4--1--1--2--2--4--4--1--1--2--2--3--3--
#   1--1--1--1--1--1--2--2--2--2--2--2--3--3--3--3--3--3--4--4--4--4--4--4--
#   3--4--2--4--2--3--3--4--1--4--1--3--2--4--1--4--1--2--2--3--1--3--1--2--

TESTS=/c/cs223/Hwk4/Tests
export LC_ALL=C

# POS > 0, LEN > 0
/usr/bin/valgrind -q \
  ./Qsort -1,2 $TESTS/t108x

echo -----

/usr/bin/valgrind -q \
  ./Qsort -2,2 $TESTS/t108x

echo =====

# POS > 0, LEN unspecified
/usr/bin/valgrind -q \
  ./Qsort -70  $TESTS/t108x

echo ------

/usr/bin/valgrind -q \
  ./Qsort -69  $TESTS/t108x

echo -----

# No -POS[,LEN]
/usr/bin/valgrind -q \
  ./Qsort      $TESTS/t108x
