#!/bin/bash
# Stable?: LEN = 0 [POS <= strlen(line)]

TESTS=/c/cs223/Hwk4/Tests
export LC_ALL=C
FILE=$TESTS/t119x

# t119x:
#   same 3 same
#   same 2 same
#   same 1 same
#   same 0 same

/usr/bin/valgrind -q \
  ./Qsort -3,0  $FILE

echo -----

/usr/bin/valgrind -q \
  ./Qsort -5,0  $FILE

echo -----

/usr/bin/valgrind -q \
  ./Qsort -5    $FILE

echo -----

/usr/bin/valgrind -q \
  ./Qsort -7,0  $FILE
